github.com:
    users:
        Akashdip1:
            oauth_token: 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
    git_protocol: https
    user: Akashdip1
    oauth_token: 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
