cookie: "sp_t=4e582665cdba0b5dead8a2cea1bf66b2; OptanonConsent=isGpcEnabled=0&datestamp=Sat+Jun+08+2024+23%3A23%3A33+GMT%2B0530+(India+Standard+Time)&version=202309.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&landingPath=NotLandingPage&groups=s00%3A1%2Cf00%3A1%2Cm00%3A1%2Ct00%3A1%2Ci00%3A1%2Cf11%3A1%2CBG169%3A1%2CBG170%3A1&AwaitingReconsent=false&geolocation=US%3BDE; sp_m=de-en; OptanonAlertBoxClosed=2024-05-25T19:03:49.854Z; sp_last_utm=%7B%22utm_campaign%22%3A%22your_account%22%2C%22utm_medium%22%3A%22menu%22%2C%22utm_source%22%3A%22spotify%22%7D; sp_gaid=0088fc16e046fd0d86288b58899408f29014acd7209d0fefd6edd7; sp_landing=https%3A%2F%2Fopen.spotify.com%2F%3Fsp_cid%3D4e582665cdba0b5dead8a2cea1bf66b2%26device%3Ddesktop; sp_key=5a4c955e-b621-4d6c-840e-7caeb73301fa"
player: spotify 
host: lyricsapi.vercel.app
ignoreErrors: true
timerInterval: 200
updateInterval: 2000
style:
  hAlignment: center
  before:
    background: ""
    foreground: ""
    bold: true
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: false
  current:
    background: ""
    foreground: ""
    bold: true
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: ""
    bold: false
    italic: false
    underline: false
    strikethrough: false
    blink: false
    faint: true
pipe:
  length: 0
  overflow: word
mpd:
  address: 127.0.0.1:6600
  password: ""
mopidy:
  address: 127.0.0.1:6680
mpris:
  players: []
browser:
  port: 8974
local:
  folder: ""
